#!/bin/bash

#------------------------------------------------------------------------------
# Populate the database:
#------------------------------------------------------------------------------

function mysql_alive() {
  local RETRIES=30; while [ ${RETRIES} -gt 0 ]; do
    timeout -t 2 bash -c "echo > /dev/tcp/${MARIADB_HOST}/${MARIADB_PORT}" &> /dev/null && return 0
    sleep 1; RETRIES=$((RETRIES - 1)); echo -n '.'
  done; echo; return 1
}

echo -n 'Waiting for the database '
mysql_alive || { echo; echo "Ops! Where is ${MARIADB_HOST}:${MARIADB_PORT} ?"; exit 1; }
mysql -h ${MARIADB_HOST} -P ${MARIADB_PORT} -u ${MARIADB_USER} -p${MARIADB_PASSWORD} ${MARIADB_DATABASE} \
-e "show tables" | grep -q 'registries' || {
  env bundle exec rake db:migrate:reset
  env bundle exec rake db:seed
}

#------------------------------------------------------------------------------
# Debug:
#------------------------------------------------------------------------------

[[ "${DEBUG}" == "true" ]] && {
  echo "### ${CONFIG_FILE}"; cat ${CONFIG_FILE}
  echo "### ${DB_CONFIG_FILE}"; cat ${DB_CONFIG_FILE}
  echo "### ${SECRETS_CONFIG_FILE}"; cat ${SECRETS_CONFIG_FILE}
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

[ "${PORT0}" ] && [ ! "${PUMA_PORT}" ] && PUMA_PORT="${PORT0}"
export SSL_CERT_DIR=${SSL_CERT_DIR:-/certs:/usr/local/share/ca-certificates:/etc/ssl/certs} && c_rehash

[[ "${PORTUS_CHECK_SSL_USAGE_ENABLED}" == "true" && "${PUMA_SSL_KEY}" && "${PUMA_SSL_CRT}" ]] && \
exec env puma -e ${RACK_ENV} -b "ssl://${PUMA_IP:-0.0.0.0}:${PUMA_PORT:-443}?key=${PUMA_SSL_KEY}&cert=${PUMA_SSL_CRT}" -w ${PUMA_WORKERS:-3} ||
exec env puma -e ${RACK_ENV} -b "tcp://${PUMA_IP:-0.0.0.0}:${PUMA_PORT:-80}" -w ${PUMA_WORKERS:-3}
